### YamlMime:Landing
title: Documentação do Docker no Azure
summary: O Docker é uma plataforma popular de geração de imagens e gerenciamento de contêineres que permite que você trabalhe rapidamente com contêineres no Linux e também no Windows. Saiba como usar o Docker no Azure.
metadata:
  title: Documentação do Docker no Azure
  description: O Docker é uma plataforma popular de geração de imagens e gerenciamento de contêineres que permite que você trabalhe rapidamente com contêineres no Linux e também no Windows.
  services: multiple
  ms.service: multiple
  ms.topic: landing-page
  author: georgewallace
  ms.author: gwallace
  ms.date: 03/08/2020
  ms.openlocfilehash: 700c5b1e113de32b80b3d716db915836049128ec
  ms.sourcegitcommit: 829d951d5c90442a38012daaf77e86046018e5b9
  ms.translationtype: HT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 10/09/2020
  ms.locfileid: "89470112"
landingContent:
- title: Implantar o Docker no Azure
  linkLists:
  - linkListType: overview
    links:
    - text: Implantar o Docker no modelo de Início rápido do Ubuntu
      url: https://azure.microsoft.com/resources/templates/docker-simple-on-ubuntu/
- title: Introdução
  linkLists:
  - linkListType: tutorial
    links:
    - text: Executar um aplicativo Web Python (Django) com PostgreSQL no Serviço de Aplicativo do Azure
      url: ../app-service/tutorial-python-postgresql-app.md
    - text: Criar uma infraestrutura de desenvolvimento em uma VM Linux no Azure com Jenkins, GitHub e Docker
      url: /azure/developer/jenkins/pipeline-with-github-and-docker
- title: Recursos
  linkLists:
  - linkListType: reference
    links:
    - text: Site do Docker do Azure
      url: https://docs.docker.com/docker-for-azure/why/
    - text: Driver do Docker do Azure
      url: https://docs.docker.com/machine/drivers/azure/
    - text: Saiba mais sobre o Docker
      url: https://docker.com
