- name: Documentação do Docker
  href: index.yml
- name: Guia de Início Rápido
  items:
    - name: Implantar uma VM Ubuntu com o Docker
      href: 'https://azure.microsoft.com/resources/templates/docker-simple-on-ubuntu/'
  expanded: true
- name: Tutoriais
  items:
    - name: Aplicativo Web do Python com Docker e PostgreSQL
      href: ../app-service/tutorial-python-postgresql-app.md?toc=%2fazure%2fpostgresql%2ftoc.json
    - name: 'CI/CD com o Docker, Jenkins e Linux'
      href: /azure/developer/jenkins/pipeline-with-github-and-docker
- name: Guias de instruções
  items:
    - name: Extensão da VM do Docker
      href: 'https://github.com/Azure/azure-docker-extension/blob/master/README.md'
    - name: Registro de contêiner do Docker
      href: ../container-registry/container-registry-get-started-portal.md
- name: Recursos
  items:
    - name: Roteiro do Azure
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Driver do Docker do Azure
      href: 'https://docs.docker.com/machine/drivers/azure/'
    - name: Site do Docker do Azure
      href: 'https://www.docker.com/docker-azure'
    - name: Site do Docker
      href: 'https://docker.com'