### YamlMime:Landing
title: Kubernetes do Azure Arc (versão prévia)
summary: Aprenda a gerenciar clusters do Kubernetes com o Azure Arc
metadata:
  title: Kubernetes do Azure Arc
  description: Aprenda a gerenciar computadores locais no Azure
  author: 
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 06/26/2020
  ms.author: 
  ms.openlocfilehash: 88d9ba51815496e7d8ec4ab3d22195c5b42c317b
  ms.sourcegitcommit: 86acfdc2020e44d121d498f0b1013c4c3903d3f3
  ms.translationtype: HT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 12/17/2020
  ms.locfileid: "97616959"
landingContent:
- title: Conectar clusters do Kubernetes ao Azure usando o Azure Arc
  linkLists:
  - linkListType: overview
    links:
    - text: O que é o Kubernetes habilitado para Azure Arc?
      url: overview.md
  - linkListType: quickstart
    links:
    - text: Início rápido
      url: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/
    - text: Conectar cluster
      url: connect-cluster.md
  - linkListType: how-to-guide
    links:
    - text: Implantar configurações usando GitOps
      url: use-gitops-connected-cluster.md
    - text: Implantar gráficos do Helm usando GitOps
      url: use-gitops-with-helm.md
    - text: Impor GitOps usando o Azure Policy
      url: use-azure-policy.md
    - text: Implantar cargas de trabalho do Azure IoT Edge
      url: deploy-azure-iot-edge-workloads.md
- title: Arquitetura de referência
  linkLists:
  - linkListType: architecture
    links:
    - text: Gerenciar as implantações e as configurações de clusters híbridos do Kubernetes
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
